ACR_DOCKER_AUTH_MASTER: &ACR_DOCKER_AUTH
  image: ${AZURE_LOGIN_SERVER_NAME}/she/circleci-build-image
  auth:
    username: ${ACR_REGISTRY_NAME}
    password: ${ACR_PASSWORD}

DOCKER_BUILD_AND_PUSH_PARAMETERS_MASTER: &DOCKER_BUILD_AND_PUSH_PARAMETERS
  image: ${ACR_REPO_BASE}/dhos-trustomer-api
  registry: ${AZURE_LOGIN_SERVER_NAME}
  tag: dev,cb-${CIRCLE_BUILD_NUM},$(git log --pretty=format:'%h' -n 1)

version: 2.1
orbs:
  azure-acr: circleci/azure-acr@0.1.4
  azure-cli: circleci/azure-cli@1.2.0
  docker: circleci/docker@2.2.0
commands:
  acr-login:
    description: Authenticate into Azure Container Registry service
    steps:
      - run:
          name: Auth with ACR
          command: az acr login -n $ACR_REGISTRY_NAME -u $AZURE_USERNAME -p $AZURE_PASSWORD
jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: |
          poetry self update --no-ansi
          pip install --upgrade tox
      - restore_cache:
          keys:
            - v1-poetry-deps-{{ checksum "poetry.lock" }}
            - v1-poetry-deps-
      - run:
          name: Run tox tests
          command: tox -r -e py39
      - save_cache:
          key: v1-poetry-deps-{{ checksum "poetry.lock" }}
          paths:
            - .tox
      - persist_to_workspace:
          root: coverage-reports
          paths:
            - coverage.xml
  integration-test:
    # We're using a machine executor because the docker-compose integration tests include mounting
    # a volume for the dummy trustomer config, which isn't supported with the remote docker executor.
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true
    resource_class: medium
    environment:
      REPORT_PORTAL_PROJECT: platform
    steps:
      - checkout
      - azure-cli/install
      - acr-login
      - run:
          name: Run the integration test script
          command: .circleci/run_integration_tests.sh
  deploy-dev:
    docker:
      - <<: *ACR_DOCKER_AUTH
    environment:
      K8S_DEV_DEPLOYMENT_NAME: deployment/dhos-trustomer-api-dep
      ACR_REPO_BASE: dhos
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.7
      - run:
          name: Add build information
          command: .circleci/record_build_info.sh
      - acr-login
      - docker/build:
          step-name: Build Docker image for ACR
          <<: *DOCKER_BUILD_AND_PUSH_PARAMETERS
      - docker/push:
          step-name: Push Docker image to ACR
          <<: *DOCKER_BUILD_AND_PUSH_PARAMETERS
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test:
          context: engineering-build
      - integration-test:
          context: engineering-build
      - deploy-dev:
          context: engineering-build
          requires:
            - test
            - integration-test
          filters:
            branches:
              only:
                - develop
