GCP_DOCKER_AUTH_MASTER: &GCP_DOCKER_AUTH
  auth:
    username: _json_key
    password: ${GOOGLE_AUTH}

version: 2.1
orbs:
  azure-cli: circleci/azure-cli@1.2.0
  azure-acr: circleci/azure-acr@0.1.4
  ms-teams: cloudradar-monitoring/ms-teams@0.0.1
jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: |
          poetry self update
          poetry config http-basic.sensynehealth ${GEMFURY_DOWNLOAD_KEY} ''
          pip install --upgrade tox
      - restore_cache:
          keys:
            - v1-poetry-deps-{{ checksum "poetry.lock" }}
            - v1-poetry-deps-
      - run:
          name: Run tox tests
          command: tox -e py39
      - save_cache:
          key: v1-poetry-deps-{{ checksum "poetry.lock" }}
          paths:
            - .tox
      - persist_to_workspace:
          root: coverage-reports
          paths:
            - coverage.xml
  integration-test:
    # We're using a machine executor because the docker-compose integration tests include mounting
    # a volume for the dummy trustomer config, which isn't supported with the remote docker executor.
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true
    resource_class: medium
    environment:
      REPORT_PORTAL_PROJECT: platform
    steps:
      - checkout
      - azure-cli/install
      - run:
          name: Azure CLI login
          command: az login --service-principal -u "${AZURE_DEV_K8S_SP}" -p "${AZURE_DEV_K8S_SP_PASSWORD}" --tenant sensynehealth.com
      - run:
          name: Auth with ACR
          command: az acr login --name "$AZURE_REGISTRY_NAME"
      - run:
          name: Run the integration test script
          command: .circleci/run_integration_tests.sh
  deploy-dev:
    docker:
      - image: gcr.io/dhos-stack/circleci-build-image:latest
        <<: *GCP_DOCKER_AUTH
    environment:
      K8S_DEV_DEPLOYMENT_NAME: deployment/dhos-trustomer-api-dep
      ACR_REPO_BASE: dhos
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.7
      - run:
          name: Add build information
          command: .circleci/record_build_info.sh
      - azure-acr/build-and-push-image:
          checkout: false
          login-server-name: ${AZURE_LOGIN_SERVER_NAME}
          registry-name: ${AZURE_REGISTRY_NAME}
          repo: ${ACR_REPO_BASE}/dhos-trustomer-api
          tag: dev,cb-${CIRCLE_BUILD_NUM},$(git log --pretty=format:'%h' -n 1)
          extra-build-args: --build-arg GEMFURY_DOWNLOAD_KEY
      - run:
          name: Deploy to UK dev cluster in Azure
          command: .circleci/deploy_azure_dev.sh uk uk-dev-api-upstream
      - ms-teams/report:
          only_on_fail: true
          webhook_url: ${MSTEAMS_NOTIFY_WEBHOOK_URL}
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test:
          context: engineering-build
      - integration-test:
          context: engineering-build
      - deploy-dev:
          context: dhos-deploy
          requires:
            - test
            - integration-test
          filters:
            branches:
              only:
                - develop
